Number of cores: 10
Number of topo files: 9
Number of replicates: 3
Number of parameters: 3334
Number of initial conditions: 100

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/csb/GRiNS/simulation_run.py", line 114, in gen_topo_param_files
    gen_julia_odesys(topo_df, topo_name, sim_dir)
    ^^^^^^^^^^^^^^^^
NameError: name 'gen_julia_odesys' is not defined. Did you mean: 'gen_diffrax_odesys'?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/csb/GRiNS/simulation_run.py", line 321, in <module>
    pool.starmap(
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
NameError: name 'gen_julia_odesys' is not defined
